(package "treesit-langs"
         "0.1.0"
         "Language bundle for Emacs's treesit.el")

(website-url "https://github.com/emacs-tree-sitter/treesit-langs")
(keywords "languages" "tools" "parsers" "tree-sitter")

(package-file "treesit-langs.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "29.1")
(depends-on "tree-sitter-langs")
