name: Update Bundle Version

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  EMACS_VER: 30.2

jobs:
  get-version:
      uses: emacs-tree-sitter/treesit-langs/.github/workflows/get_version.yml@main

  main:
    needs: [get-version]
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.get-version.outputs.version }}
    steps:
    - uses: jcs090218/setup-emacs@master
      with:
        version: ${{ env.EMACS_VER }}

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - uses: actions/checkout@v6

    - name: Expose bundle version
      run: |
        echo "BUNDLE_VER=${{ env.VERSION }}" >> $GITHUB_ENV

    - name: Update Bundle Version
      run: |
        eask install-deps --dev
        eask run script update-bundle-version

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v8
      with:
        title: 'Update Bundle Version to ${{ env.VERSION }}'
        body: ''
        commit-message: 'Update Bundle Version to ${{ env.VERSION }}'
        branch: update-bundle-version
        delete-branch: true
